# Generated by Django 2.1.7 on 2021-04-07 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0002_auto_20210407_2036'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['date']},
        ),
        migrations.RenameField(
            model_name='job',
            old_name='created_date',
            new_name='date',
        ),
    ]
