# Generated by Django 2.1.7 on 2021-04-07 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scraping', '0003_auto_20210407_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='date',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='job',
            name='encours',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='job',
            name='taux',
            field=models.CharField(default='-', max_length=30),
        ),
        migrations.AlterField(
            model_name='job',
            name='volume',
            field=models.CharField(default='-', max_length=30),
        ),
    ]
